version: '3'
services:
  # mocha (mount all files for testing)
  mocha:
    # image: node:9.9.0-alpine
    build: .docker/mocha
    working_dir: /mocha
    volumes:
      - .:/mocha/
      # - /mocha/node_modules
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oreilly
    depends_on:
      - db

  # MySQL
  db:
    image: mysql:5.7.21
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./tests/_data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=cytec
      - MYSQL_PASSWORD=cytec
      - MYSQL_DATABASE=oreilly
